// frameworks/frontend/nuxt-example/app/app.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { client } from 'integrate-sdk'

interface Repo {
  name?: string
  full_name?: string
  description?: string
  html_url?: string
}

const githubAuthorized = ref(false)
const repos = ref<Repo[]>([])
const loadingRepos = ref(false)
const reposError = ref<string | null>(null)

async function updateButtonStates(context = 'unknown') {
  try {
    githubAuthorized.value = await client.isAuthorized('github')
  } catch (error) {
    console.error(`[updateButtonStates] Error checking authorization (context: ${context}):`, error)
  }
}

async function handleGithubClick() {
  try {
    if (githubAuthorized.value) {
      await client.disconnectProvider('github')
      await updateButtonStates('after-disconnect')
    } else {
      await client.authorize('github')
    }
  } catch (error) {
    console.error('Error:', error)
  }
}

async function handleListRepos() {
  loadingRepos.value = true
  reposError.value = null
  repos.value = []

  try {
    const response = await client.github.listOwnRepos()

    // Extract repos from MCPToolCallResponse
    let extractedRepos: Repo[] = []

    if (
      response.structuredContent &&
      Array.isArray(response.structuredContent)
    ) {
      extractedRepos = response.structuredContent as Repo[]
    } else if (response.content && response.content.length > 0) {
      // Try to parse JSON from text content
      const textContent = response.content[0]?.text
      if (textContent) {
        try {
          const parsed = JSON.parse(textContent)
          extractedRepos = Array.isArray(parsed)
            ? parsed
            : parsed.repos || parsed.repositories || []
        } catch {
          extractedRepos = []
        }
      }
    }

    if (extractedRepos.length > 0) {
      repos.value = extractedRepos
    } else {
      reposError.value = 'No repositories found or unexpected response format.'
      console.log('Response:', response)
    }
  } catch (error) {
    console.error('Error listing repos:', error)
    reposError.value = error instanceof Error ? error.message : String(error)
  } finally {
    loadingRepos.value = false
  }
}

onMounted(() => {
  // Initial auth check
  updateButtonStates('initial-mount')

  const handleFocus = () => {
    updateButtonStates('window-focus')
  }

  if (typeof window !== 'undefined') {
    window.addEventListener('focus', handleFocus)
  }

  const timeout = setTimeout(() => {
    updateButtonStates('delayed-mount-check')
  }, 500)

  onUnmounted(() => {
    if (typeof window !== 'undefined') {
      window.removeEventListener('focus', handleFocus)
    }
    clearTimeout(timeout)
  })
})
</script>

<template>
  <button @click="handleGithubClick">
    {{ githubAuthorized ? 'Disconnect Github' : 'Connect Github' }}
  </button>

  <div v-if="githubAuthorized" class="repos-section">
    <button @click="handleListRepos" :disabled="loadingRepos">
      {{ loadingRepos ? 'Loading...' : 'List All Repos' }}
    </button>

    <div v-if="reposError" class="repos-output">
      <p>{{ reposError }}</p>
    </div>

    <div v-else-if="repos.length > 0" class="repos-output">
      <h3>Repositories ({{ repos.length }}):</h3>
      <ul>
        <li v-for="(repo, index) in repos" :key="index">
          <strong>{{ repo.name || repo.full_name || 'Unknown' }}</strong>
          <template v-if="repo.description">
            <br />
            <small>{{ repo.description }}</small>
          </template>
          <template v-if="repo.html_url">
            <br />
            <a
              :href="repo.html_url"
              target="_blank"
              rel="noopener noreferrer"
            >
              View on GitHub
            </a>
          </template>
        </li>
      </ul>
    </div>
  </div>
</template>

// frameworks/frontend/nextjs-example/src/app/page.tsx
"use client";

import { useState, useEffect } from "react";
import { client } from "integrate-sdk";

interface Repo {
  name?: string;
  full_name?: string;
  description?: string;
  html_url?: string;
}

export default function Home() {
  const [githubAuthorized, setGithubAuthorized] = useState(false);
  const [repos, setRepos] = useState<Repo[]>([]);
  const [loadingRepos, setLoadingRepos] = useState(false);
  const [reposError, setReposError] = useState<string | null>(null);

  async function updateButtonStates(context = "unknown") {
    try {
      const authorized = await client.isAuthorized("github");
      setGithubAuthorized(authorized);
    } catch (error) {
      console.error(`[updateButtonStates] Error checking authorization (context: ${context}):`, error);
    }
  }

  async function handleGithubClick() {
    if (githubAuthorized) {
      await client.disconnectProvider("github");
      await updateButtonStates("after-disconnect");
    } else {
      await client.authorize("github");
    }
  }

  async function handleListRepos() {
    setLoadingRepos(true);
    setReposError(null);
    setRepos([]);

    try {
      const response = await client.github.listOwnRepos();

      // Extract repos from MCPToolCallResponse
      let extractedRepos: Repo[] = [];

      if (
        response.structuredContent &&
        Array.isArray(response.structuredContent)
      ) {
        extractedRepos = response.structuredContent as Repo[];
      } else if (response.content && response.content.length > 0) {
        // Try to parse JSON from text content
        const textContent = response.content[0]?.text;
        if (textContent) {
          try {
            const parsed = JSON.parse(textContent);
            extractedRepos = Array.isArray(parsed)
              ? parsed
              : parsed.repos || parsed.repositories || [];
          } catch {
            extractedRepos = [];
          }
        }
      }

      if (extractedRepos.length > 0) {
        setRepos(extractedRepos);
      } else {
        setReposError("No repositories found or unexpected response format.");
        console.log("Response:", response);
      }
    } catch (error) {
      console.error("Error listing repos:", error);
      setReposError(error instanceof Error ? error.message : String(error));
    } finally {
      setLoadingRepos(false);
    }
  }

  useEffect(() => {
    updateButtonStates("initial-mount");

    const handleFocus = () => {
      updateButtonStates("window-focus");
    };

    window.addEventListener("focus", handleFocus);

    const timeout = setTimeout(() => {
      updateButtonStates("delayed-mount-check");
    }, 500);

    return () => {
      window.removeEventListener("focus", handleFocus);
      clearTimeout(timeout);
    };
  }, []);

  return (
    <>
      <button
        onClick={handleGithubClick}
        className="px-8 py-4 rounded-lg border-none bg-black text-white text-xl cursor-pointer"
      >
        {githubAuthorized ? "Disconnect Github" : "Connect Github"}
      </button>

      {githubAuthorized && (
        <div className="mt-8">
          <button
            onClick={handleListRepos}
            disabled={loadingRepos}
            className="px-8 py-4 rounded-lg border-none bg-black text-white text-xl cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {loadingRepos ? "Loading..." : "List All Repos"}
          </button>

          {reposError ? (
            <div className="mt-4 p-4 bg-[#f5f5f5] rounded-lg max-h-[400px] overflow-y-auto">
              <p>{reposError}</p>
            </div>
          ) : repos.length > 0 ? (
            <div className="mt-4 p-4 bg-[#f5f5f5] rounded-lg max-h-[400px] overflow-y-auto">
              <h3 className="mt-0">Repositories ({repos.length}):</h3>
              <ul className="list-none p-0">
                {repos.map((repo, index) => (
                  <li
                    key={index}
                    className="p-2 mb-2 bg-white rounded"
                  >
                    <strong>{repo.name || repo.full_name || "Unknown"}</strong>
                    {repo.description && (
                      <>
                        <br />
                        <small>{repo.description}</small>
                      </>
                    )}
                    {repo.html_url && (
                      <>
                        <br />
                        <a
                          href={repo.html_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-[#0066cc]"
                        >
                          View on GitHub
                        </a>
                      </>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          ) : null}
        </div>
      )}
    </>
  );
}
